"use client"
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1FamF2AMxvx
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:
"use client"
import { Archivo } from 'next/font/google'
import { Arimo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import { Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function Shubham() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
     
      <main className="flex-1 bg-[#fdfcdc]">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <Carousel className="mx-auto aspect-[4/3] overflow-hidden rounded-xl sm:w-full lg:order-last">
                <CarouselContent>
                  <CarouselItem>
                    <img src="/h1.jpeg" width="800" height="600" alt="Hero" className="object-cover" />
                  </CarouselItem>
                  <CarouselItem>
                    <img src="/placeholder.svg" width="800" height="600" alt="Hero" className="object-cover" />
                  </CarouselItem>
                  <CarouselItem>
                    <img src="/placeholder.svg" width="800" height="600" alt="Hero" className="object-cover" />
                  </CarouselItem>
                </CarouselContent>
                <CarouselPrevious />
                <CarouselNext />
              </Carousel>
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    Skyways Film Production
                  </h1>
                  <p className="max-w-[600px] text-[#00afb9] md:text-xl">
                    Discover the best models for your next project. Our diverse and talented roster is ready to bring
                    your vision to life.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#00afb9] text-[#fdfcdc]">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Our Models</h2>
                <p className="max-w-[700px] text-[#fdfcdc] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Browse our diverse portfolio of professional models available for your next project.
                </p>
              </div>
            </div>
            <div className="mx-auto grid grid-cols-2 gap-4 py-12 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">
              <img
                src="/m1.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m2.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m3.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m4.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m5.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m6.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m7.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m8.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m9.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m10.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m11.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m12.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m13.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m14.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m15.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
           
            </div>

          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#fdfcdc] text-[#00afb9]">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Our Client</h2>
                <p className="max-w-[700px] text-[#fdfcdc] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Browse our diverse portfolio of professional models available for your next project.
                </p>
              </div>
            </div>
            <div className="mx-auto grid grid-cols-2 gap-4 py-12 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">
              <img
                src="/m1.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m2.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m3.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m4.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m5.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m6.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m7.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m8.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m9.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m10.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m11.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m12.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m13.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m14.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
              <img
                src="/m15.jpg"
                width="300"
                height="300"
                alt="Model"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center"
              />
           
            </div>

          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#fed9b7] text-[#0081a7]">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">What Our Clients Say</h2>
                <p className="max-w-[700px] text-[#0081a7] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Hear from our satisfied clients about their experience working with Skyways Film Production.
                </p>
              </div>
            </div>
            <div className="mx-auto grid grid-cols-1 gap-6 py-12 sm:grid-cols-2 md:grid-cols-3">
              <Card className="p-6 space-y-4 bg-[#f07167] text-[#fdfcdc]">
                <blockquote className="text-lg font-semibold leading-snug lg:text-xl lg:leading-normal xl:text-2xl">
                  &ldquo;Skyways Film Production provided us with the perfect models for our latest campaign. They were
                  professional, reliable, and a joy to work with.&rdquo;
                </blockquote>
                <div>
                  <div className="font-semibold">Jane Doe</div>
                  <div className="text-sm text-[#fdfcdc]">Marketing Director, Acme Corp</div>
                </div>
              </Card>
              <Card className="p-6 space-y-4 bg-[#f07167] text-[#fdfcdc]">
                <blockquote className="text-lg font-semibold leading-snug lg:text-xl lg:leading-normal xl:text-2xl">
                  &ldquo;I've worked with Skyways Film Production for years, and they never fail to deliver top-notch
                  talent. Highly recommended!&rdquo;
                </blockquote>
                <div>
                  <div className="font-semibold">John Smith</div>
                  <div className="text-sm text-[#fdfcdc]">Creative Director, Acme Advertising</div>
                </div>
              </Card>
              <Card className="p-6 space-y-4 bg-[#f07167] text-[#fdfcdc]">
                <blockquote className="text-lg font-semibold leading-snug lg:text-xl lg:leading-normal xl:text-2xl">
                  &ldquo;Skyways Film Production has an incredible roster of models. They made our photoshoot a breeze
                  and the results were amazing.&rdquo;
                </blockquote>
                <div>
                  <div className="font-semibold">Sarah Lee</div>
                  <div className="text-sm text-[#fdfcdc]">Art Director, Acme Fashion</div>
                </div>
              </Card>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#0081a7] text-[#fdfcdc]">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Why Choose Skyways?</h2>
                <p className="max-w-[700px] text-[#fdfcdc] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Discover why Skyways Film Production is the top choice for your next project.
                </p>
              </div>
            </div>
            <div className="mx-auto grid grid-cols-1 gap-6 py-12 sm:grid-cols-2 md:grid-cols-3">
              <Card className="p-6 space-y-4 bg-[#f07167] text-[#fdfcdc]">
                <div className="flex items-center">
                  <ThumbsUpIcon className="h-8 w-8 mr-4" />
                  <h3 className="text-xl font-bold">Experienced Models</h3>
                </div>
                <p className="text-[#fdfcdc]">
                  Our models have years of experience in the industry, ensuring professional and reliable results.
                </p>
              </Card>
              <Card className="p-6 space-y-4 bg-[#f07167] text-[#fdfcdc]">
                <div className="flex items-center">
                  <CalendarIcon className="h-8 w-8 mr-4" />
                  <h3 className="text-xl font-bold">Flexible Scheduling</h3>
                </div>
                <p className="text-[#fdfcdc]">
                  We work with your schedule to ensure a seamless photoshoot or filming experience.
                </p>
              </Card>
              <Card className="p-6 space-y-4 bg-[#f07167] text-[#fdfcdc]">
                <div className="flex items-center">
                  <StarIcon className="h-8 w-8 mr-4" />
                  <h3 className="text-xl font-bold">Top-Notch Service</h3>
                </div>
                <p className="text-[#fdfcdc]">
                  Our team is dedicated to providing exceptional service and support throughout your project.
                </p>
              </Card>
            </div>
          </div>
        </section>
     
      </main>
    </div>
  )
}

function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


function ThumbsUpIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 10v12" />
      <path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>
  )
}
